### ISSUE TITLE
Source code release? (It's GPL'd code)

### ISSUE THREAD

**Issue by jite** [bmorello/MVDSV-0.40-Xcore#2]
First off; awesome that there's people showing interest in Quakeworld! Currently we're in quite a bad position with not even a handful amount of developers left (of which basically no one has (had) enough time to put into this). Seeing that you only upload compiled binaries makes me a bit sad, it would be nice if we could review and integrate patches to make the software (and Quakeworld scene) more attractive and better for everyone.

Github really needs a messaging system (or if its just me that can't find it?) :)

Feel free to drop by at http://discord.quake.world (I'm dimman)

**Comment by jite** [comment]
No really, I wasn't kidding.

**Comment by bmorello** [comment]
The mere act of communicating with other programs does not, by itself, require all software to be GPL; nor does distributing GPL software with non-GPL software.

By the way, I'm not a developer. Now if you care to share something of value, such as contributing to my vision go ahead and do so.

By the way, open source modified github binaries helps people with raspberry pi's get by when software is not released with "apt-get". Since most of my interest was using the raspberry pi good luck to you sir.

Also, where's my bot game code? Because I believe you are spike in disguise.

**Comment by jite** [comment]
@bmorello Your released binaries either contains code from mvdsv or is a direct modification of mvdsv itself, correct?

Don't get me wrong, I think it's good what you're doing (I think that was clear from the initial text :) ), however modifying GPL licensed source code and releasing binaries means that you _must_ release the source code with your modifications.

You can find Spike on Quakenet, #fte :) I'm not him though, wish I was at times...

**Comment by bmorello** [comment]
Take me to court then.

**Comment by jite** [comment]
I have no interest in that, we're simply interested in the changes you've made, to help improve the community, which is basically what open source and this community is all about. You've made changes to code that people have made open source and we ask you to respect that.

**Comment by bmorello** [comment]
I'm simply not interested in talking further about it. Perhaps you could share some benchmarks and challenge the results? Or maybe just run it through the ringer to let me know just how far I should take it further.... though I believe It's currently overkill for a pi3.

**Comment by jite** [comment]
That's sad. I don't think the qw community has any interest in you either then, which is a shame cause your work could perhaps have improved things for people and gotten support from the community.

Let me know if you come to your senses and change your mind.

**Comment by bmorello** [comment]
I clearly don't need what you believe to be respect. Thanks for your time in trying to rip off my code, without offering me anything in exchange.

**Comment by jite** [comment]
No you obviously don't, you just need to rip people off. I offer you pity only, but I don't think that makes you happier.

**Comment by jite** [comment]
**I would strongly discourage anyone from using this as it may very well contain malware/spyware or any other sort of ill intent. The author clearly has no good intentions.**

**Comment by bmorello** [comment]
Actually that's you. I simply have made what I wanted to make and if it contained those things, I'd be legally liable and unfortunately taken to prison given my position in society.
